### ISSUE TITLE
Gitorious is no more

### ISSUE THREAD

**Issue by ghost** [simontunnat/fehlstart-git#1]
Looks like Gitorious is no longer a thing and is being archived. Do you happen to have the original source for this little gem? I wish I had saved it.

**Comment by simontunnat** [comment]
Sadly: no. I really wish I had copied it. I just created this repo because I planned to overtake the archlinux package after the move to the aur 4.0 version.

**Comment by simontunnat** [comment]
"shaggytwodope" on aur helped use out. fehlstart moved to GitLab before the Gitorious shutdown:
https://gitlab.com/fehlstart/fehlstart

I updated the package wit the new location (see 78df9e2).

**Comment by ghost** [comment]
Thanks for tracking it down!
